### ISSUE TITLE
@!refreshed is not set correctly

### ISSUE THREAD

**Issue by antoniogamiz** [finanalyst/raku-pod-from-cache#4]
Pod paths are added here: 
https://github.com/finanalyst/raku-pod-from-cache/blob/84845e546cd4b0662bba6b2b75b493304e1d8d64/lib/Pod/From/Cache.pm6#L71-L80

But the condition `$! or ! $checksum.defined` does not catch when an existing pod file has been modified. This code:
https://github.com/finanalyst/raku-pod-from-cache/blob/84845e546cd4b0662bba6b2b75b493304e1d8d64/lib/Pod/From/Cache.pm6#L68-L70

does not throw an exception if a pod has been modified. To reproduce the bug, you can run:
~~~raku
use Pod::From::Cache;
use File::Directory::Tree;

constant DOC="raku-test-doc";
constant CACHE="raku-test-cache";
mkdir DOC;

new-pod("first");

my $cache = Pod::From::Cache.new(:doc-source(DOC), :cache-path(CACHE));

say $cache.list-files;

new-pod("second");

$cache .= new(:doc-source(DOC), :cache-path(CACHE));

say $cache.list-files;

rmtree DOC;
rmtree CACHE;

sub new-pod($path) {
(DOC ~ "/{$path}.pod6").IO.spurt(q:to/POD-CONTENT/);
    =begin pod
    random text
    =end pod
    POD-CONTENT
}
~~~
And you will see that the last `say` statement outputs both files when it should return only the last one.

**Comment by finanalyst** [comment]
I don't see a problem.
`new-pod` creates two separate files `first.pod6` and `second.pod6`. Two files with different names, so they will both be cached.

This is the expected behaviour. 

Note: The checksum is used to determine whether the version on disk of a file with a given name is different to the content in the cache. The checksum is not determining whether two files with different names have the same content.  I do not think that this would be desirable as we may want to files with the same content to exist but with different names.

**Comment by finanalyst** [comment]
I changed your test file as follows. A file with the same name has its content changed, and the changed is trapped.
(I move the rmtree calls up so that I could see what was in the directories after running)
```
use Pod::From::Cache;
use File::Directory::Tree;

constant DOC="raku-test-doc";
constant CACHE="raku-test-cache";

rmtree DOC;
rmtree CACHE;

mkdir DOC;

new-pod("first", '');

my $cache = Pod::From::Cache.new(:doc-source(DOC), :cache-path(CACHE));

say $cache.list-files;

new-pod("first", "second");

$cache .= new(:doc-source(DOC), :cache-path(CACHE));

say $cache.list-files;

sub new-pod($path, $content) {
    (DOC ~ "/{$path}.pod6").IO.spurt(qq:to/POD-CONTENT/);
    =begin pod
    random text {$content}
    =end pod
    POD-CONTENT
}
```

**Comment by finanalyst** [comment]
Yes this is a problem with the Precompilation Modules - I think.

I found that when I wanted to change the cache in the SAME program, the change did not occur. 

I spent ages trying to determine how to get round it. I could not with out writing my own Precompilation Module.

I am updating the Documentation to reflect the problem.

You will see that in the tests that in order for the refresh to work, that is to change the content of a cached program, ANOTHER  program has to be run!

**Comment by antoniogamiz** [comment]
So how can I know what pod files have changed? That's a key feature for `documentable update`. Maybe an index file will have to be used, containing a timestamp or something like that.

**Comment by finanalyst** [comment]
I split your program into two.

The first creates 'first.pod6' and it reports it has changed.
The second gets the cache and creates 'second'. 'first' is already in cache and unchanged AT THE START the second program.
Only second is changed, and this is listed.

This is the behaviour you are seeking.


tester1.raku
```
use Pod::From::Cache;
use File::Directory::Tree;
constant DOC="raku-test-doc";
constant CACHE="raku-test-cache";
rmtree DOC;
rmtree CACHE;
say 'in first';
mkdir DOC;
new-pod("first");
my $cache = Pod::From::Cache.new(:doc-source(DOC), :cache-path(CACHE));
say $cache.list-files;
#new-pod("second");
#$cache .= new(:doc-source(DOC), :cache-path(CACHE));
#say $cache.list-files;

sub new-pod($path) {
    (DOC ~ "/{$path}.pod6").IO.spurt(qq:to/POD-CONTENT/);
    =begin pod
    random text
    =end pod
    POD-CONTENT
}
```
tester2.raku
```
use Pod::From::Cache;
use File::Directory::Tree;
constant DOC="raku-test-doc";
constant CACHE="raku-test-cache";
say 'second';
# new-pod("first");
my $cache ;#= Pod::From::Cache.new(:doc-source(DOC), :cache-path(CACHE));
# say $cache.list-files;
new-pod("second");
$cache .= new(:doc-source(DOC), :cache-path(CACHE));
say $cache.list-files;
sub new-pod($path) {
    (DOC ~ "/{$path}.pod6").IO.spurt(qq:to/POD-CONTENT/);
    =begin pod
    random text
    =end pod
    POD-CONTENT
}
```
`raku -Ilib tester1.raku; raku -Ilib tester2.raku`
Output:
```
in first
[raku-test-doc/first.pod6]
in second
[raku-test-doc/second.pod6]
```

**Comment by finanalyst** [comment]
The in-program behaviour of the cache is not intutive. 
The desired behaviour does happen.
The non-intituive behaviour comes from Precomp modules

**Comment by antoniogamiz** [comment]
I will have to make a hack for testing `documentable update` then mmm.
