### ISSUE TITLE
Verbose option

### ISSUE THREAD

**Issue by coke** [finanalyst/raku-pod-from-cache#5]
I would appreciate a verbose option that let me know what was going on with the pod cache, locking, etc - running it against the raku/doc repository is slow, and it would be nice to have an idea of the progress.

**Comment by finanalyst** [comment]
I have included a spinner to show progress.
The compilation used Async, so multiple threads.
More verbose?

**Comment by coke** [comment]
Spinner is probably fine, thanks.
