### ISSUE TITLE
list-files should be called list-changed-files

### ISSUE THREAD

**Issue by JJ** [finanalyst/raku-pod-from-cache#8]
It's a change in API, but it really clarifies what it's doing.

https://github.com/finanalyst/raku-pod-from-cache/blob/567ada20e64caa32b15da49f1d3eac1a4da44abd/lib/Pod/From/Cache.pm6#L111

**Comment by finanalyst** [comment]
agreed

**Comment by finanalyst** [comment]
added list-changed-files, left in list-files, changed documentation to new method. So list-files will be documented as a reference to list-changed-files
